### ISSUE TITLE
Error Instalación en Docker

### ISSUE THREAD

**Issue by darkjhesus** [gabrieldelaparra/Ordos#47]
Al instalar en Docker, obtengo el siguiente error:
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found

Podrías ayudarme con la solución.?

**Comment by gabrieldelaparra** [comment]
Hola,

Gracias por tu mensaje. Me parece que aquí está la solución a tu problema:
https://stackoverflow.com/questions/49603170/docker-could-not-find-plugin-bridge-in-v1-plugin-registry-plugin-not-found

Avísame porfa si te funciona.

Saludos,

**Comment by darkjhesus** [comment]
Muchas gracias por tu ayuda, efectivamente el problema fue que el docker estaba para Windows,  cambié a Linux y se solucionó el problema.

**Comment by darkjhesus** [comment]
Quizás tengas la librería iec61850 para python ?

**Comment by gabrieldelaparra** [comment]
Hola, no en verdad, la que estoy ocupando es de un repo de aca de github. Puedes ocupar python desde c# o alverre. Puedes googlear sobre eso.
